In [184]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")


In [185]:
!pip install joblib



In [248]:
class perceptrons:
    def __init__(self, eta: float=None, epochs: int=None):
            self.weights=np.random.randn(3)*1e-4
            self.eta=eta
            self.epochs=epochs
            
    def _z_outcomes(self,inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
            
    def fit(self, X, y):
            self.X=X
            self.y=y
            
            X_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
            print(f"X with bias:\n{X_with_bias}")
            
            for epoch in range(self.epochs):
                print("----"*10)
                print(f"for each epoch>>{epoch+1}")
                print("--"*10)
                
                z =self._z_outcomes(X_with_bias, self.weights)
                y_hat=self.activation_function(z)
                print(f"predicted value after forward pass: \n {y_hat}")
                
                self.error=self.y-y_hat
                print(f"error: \n {self.error}")
                                
                self.weights=self.weights+self.eta*np.dot(X_with_bias.T, self.error)
                print(f" updated weight after epoch:{epoch+1}/{self.epochs}:\n {self.weights}")
                print(f"##"*10)
                
    def predict(self, X):
        X_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
        z = self._z_outcomes(X_with_bias,self.weights)
        return self.activation_function(z)

In [249]:
OR ={
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [250]:
def prepare_data(df, target_col="y"):
    X=df.drop(target_col, axis=1)
    y=df[target_col]
    return X,y

In [251]:
X, y= prepare_data(df_OR)
ETA=0.1
EPOCHS=10

model_or=perceptrons(eta=ETA, epochs=EPOCHS)
model_or.fit(X,y)


X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
----------------------------------------
for each epoch>>1
--------------------
predicted value after forward pass: 
 [1 1 1 1]
error: 
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
 updated weight after epoch:1/10:
 [-7.61170625e-05 -2.08285721e-04  9.97148077e-02]
####################
----------------------------------------
for each epoch>>2
--------------------
predicted value after forward pass: 
 [0 0 0 0]
error: 
 0    0
1    1
2    1
3    1
Name: y, dtype: int64
 updated weight after epoch:2/10:
 [ 0.19992388  0.19979171 -0.20028519]
####################
----------------------------------------
for each epoch>>3
--------------------
predicted value after forward pass: 
 [1 1 1 1]
error: 
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
 updated weight after epoch:3/10:
 [ 0.19992388  0.19979171 -0.10028519]
####################
----------------------------------------
for each epoch>>4
------------

In [252]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [253]:
model_or.predict(X)

array([0, 1, 1, 1])

In [247]:
-np.ones((4,1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [ ]:
X= np.ones((4,2))
X

In [ ]:
obj=perceptrons(eta=0.01, epochs=10)

In [ ]:
obj.eta

In [ ]:
obj.epochs

In [ ]:
obj.weights

In [165]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [166]:
y=np.ones((4,1))

In [167]:
obj.fit(X,y)

X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]


In [168]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])

SyntaxError: invalid syntax (3694999374.py, line 1)