In [6]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
plt.style.use("fivethirtyeight")

In [5]:
!pip install joblib


In [80]:
class perceptrons:
    def __init__(self, eta: float=None, epochs: int=None):
            self.weights=np.random.randn(3)*1e-4
            self.eta=eta
            self.epochs=epochs
            
    def fit(self, X, y):
            self.X=x
            self.y=y
            
            x_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
            print(f"X with bias:\n{x_with_bias}")

In [81]:
-np.ones((4,1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [82]:
X= np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [89]:
obj=perceptrons(eta=0.01, epochs=10)

In [90]:
obj.eta

0.01

In [91]:
obj.epochs

10

In [94]:
obj.weights

array([ 5.81036035e-05, -4.52228638e-05,  8.23924690e-05])

In [95]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [96]:
y=np.ones((4,1))

In [97]:
obj.fit(X,y)

X with bias:
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [98]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])