In [6]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
plt.style.use("fivethirtyeight")

In [5]:
!pip install joblib


In [99]:
class perceptrons:
    def __init__(self, eta: float=None, epochs: int=None):
            self.weights=np.random.randn(3)*1e-4
            self.eta=eta
            self.epochs=epochs
            
    def fit(self, X, y):
            self.X=X
            self.y=y
            
            x_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
            print(f"X with bias:\n{x_with_bias}")

In [100]:
-np.ones((4,1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [101]:
X= np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [102]:
obj=perceptrons(eta=0.01, epochs=10)

In [103]:
obj.eta

0.01

In [104]:
obj.epochs

10

In [105]:
obj.weights

array([ 2.75469369e-05, -1.10665042e-04, -1.13551494e-05])

In [106]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [107]:
y=np.ones((4,1))

In [108]:
obj.fit(X,y)

X with bias:
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [109]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])